add_test([=[HelloTest.BasicAssertions]=]  /Users/alexseres/OwnCplusPlusProjects/ToDoProject/test/build/hello_test [==[--gtest_filter=HelloTest.BasicAssertions]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HelloTest.BasicAssertions]=]  PROPERTIES WORKING_DIRECTORY /Users/alexseres/OwnCplusPlusProjects/ToDoProject/test/build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UserHandlerTest.check_connection]=]  /Users/alexseres/OwnCplusPlusProjects/ToDoProject/test/build/hello_test [==[--gtest_filter=UserHandlerTest.check_connection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UserHandlerTest.check_connection]=]  PROPERTIES WORKING_DIRECTORY /Users/alexseres/OwnCplusPlusProjects/ToDoProject/test/build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  hello_test_TESTS HelloTest.BasicAssertions UserHandlerTest.check_connection)
